[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions"

[[redirects]]
  from = "/stripe-webhook/*"
  to = "https://www.projectschool.dev/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]

  [headers]
  # Set headers for all routes
  [[headers.values]]
    for = "/*"
    [headers.values]
      Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "no-referrer-when-downgrade"
      Permissions-Policy = "geolocation=(), microphone=(), camera=()"
      Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com https://js.stripe.com https://cdn.buymeacoffee.com https://codesandbox.io https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://upload.wikimedia.org https://images.pexels.com https://images.unsplash.com; frame-src 'self' https://www.youtube.com https://codesandbox.io/embed https://js.stripe.com; connect-src 'self' https://projectschool404-4c33494b2162.herokuapp.com https://api.github.com https://www.googleapis.com https://firebase.googleapis.com https://*.firebaseio.com; base-uri 'self'; form-action 'self'; object-src 'none'"

