[build.environment]
  NODE_VERSION = "20.14"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"

[build]
  functions = "functions"
  command = "npm run build"
  publish = "."

[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Content-Type = "application/json"

