[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions"

[[redirects]]
  from = "/stripe-webhook/*"
  to = "https://www.projectschool.dev/:splat"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://js.stripe.com https://cdn.buymeacoffee.com https://codesandbox.io https://unpkg.com https://cdnjs.cloudflare.com https://apis.google.com https://www.gstatic.com https://firebase.googleapis.com;
      connect-src 'self' https://identitytoolkit.googleapis.com https://projectschool404-4c33494b2162.herokuapp.com https://api.github.com https://www.googleapis.com https://firebase.googleapis.com https://*.firebaseio.com https://securetoken.googleapis.com;
      font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      img-src 'self' data: https://www.gstatic.com https://firebase.googleapis.com;
      object-src 'none';
      media-src 'none';
      child-src 'none';
      form-action 'self';
      frame-ancestors 'self';
      upgrade-insecure-requests;
      block-all-mixed-content;
    """

    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]
