[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions"

[[redirects]]
  from = "/stripe-webhook/*"
  to = "https://www.projectschool.dev/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      frame-ancestors 'self' https://pay.google.com;
      script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com https://js.stripe.com https://cdn.buymeacoffee.com https://codesandbox.io https://unpkg.com https://cdnjs.cloudflare.com https://apis.google.com https://www.gstatic.com https://firebase.googleapis.com https://*.google-analytics.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
      font-src 'self' https://fonts.gstatic.com https://fonts.googleapis.com;
      img-src 'self' data: https://upload.wikimedia.org https://images.pexels.com https://images.unsplash.com https://cdn.buymeacoffee.com https://www.google.com/images/;
      frame-src 'self' https://www.youtube.com https://*.codesandbox.io https://codesandbox.io https://js.stripe.com https://projectschool-48842.firebaseapp.com;
      connect-src 'self' https://*.codesandbox.io https://codesandbox.io https://projectschool404-4c33494b2162.herokuapp.com https://api.github.com https://www.googleapis.com https://firebase.googleapis.com https://*.firebaseio.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com https://firestore.googleapis.com https://region1.google-analytics.com https://www.google-analytics.com;
      base-uri 'self';
      form-action 'self';
      object-src 'none';
    """
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]