[build.environment]
  NODE_VERSION = "20.14"

[functions]
  node_bundler = "esbuild"

[build]
  functions = "functions"
  command = "npm run build"
  publish = "build/"

[[headers]]
  for = "/.netlify/functions/stripe-webhook"
  [headers.values]
    Content-Type = "application/json"

