[build]
  command = "npm run build"
  publish = "build/"
  functions = "netlify/functions"

[[redirects]]
  from = "/stripe-webhook/*"
  to = "https://www.projectschool.dev/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]